settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: template-echo
  path: .
  commands:
    install:
      status: true
      method: go build -o <path/to/built/binary>
    run:
      status: true
      method: <path/to/built/binary>
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .gitignore
    - .realize
    - go.med
    - go.sum
    - vendor
    - README.md
